# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e2aa72bc7a8864c99552da4631471625921df2f8e5b0766438165971eb9a3f158d499a0565faacc3a27dfca514c057826b62d3a199a066ebac00bfa8f1f0a57d
  telstra_public_key: g29lXBi4IZo0zXkJyeDza9dB1RiQFswa
  telstra_private_key: LAqQtlbWhG9EUOM0
test:
  secret_key_base: d6774ead10a369f299f325430b41f4f4003badc4be2f5df4132fa585d1e85ed6381f0f1c7e3e5e228eb59b014f2588dcbde8507d185496dadd6e16bf76961c29

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  telstra_public_key: <%= ENV["TELSTRA_PUB"] %>
  telstra_private_key: <%= ENV["TELSTRA_PRIV"] %>
